version: "3"
services:
  postgres:
    image: postgres:12-alpine
    container_name: hw-8
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1239
      POSTGRES_DB: db-hw-8
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: fastapi_app
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: db-hw-8
      DB_USER: postgres
      DB_PASSWORD: 1239
      PORT: 8000
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - .:/app

volumes:
  postgres-data:
    driver: local
